### ISSUE TITLE
ERROR! the role 'tna76874.ansible_docker_jitsi

### ISSUE THREAD

**Issue by olegsidokhmetov** [tna76874/ansible-docker-jitsi#1]
ERROR! the role 'tna76874.ansible_docker_jitsi' was not found in /etc/ansible/playbook/ansible-docker-jitsi/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/etc/ansible/playbook/ansible-docker-jitsi

The error appears to be in '/etc/ansible/playbook/ansible-docker-jitsi/start-deploy-jitsi.yaml': line 25, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - tna76874.ansible_docker_jitsi
      ^ here

I can not understand how it does will work. Do you have manual step by step?

**Comment by tna76874** [comment]
Hi,

before using the role you have either install this role from ansible-galaxy or clone the repo in your roles folder.

https://galaxy.ansible.com/tna76874/ansible_docker_jitsi

**Comment by olegsidokhmetov** [comment]
> Hi,
> 
> before using the role you have either install this role from ansible-galaxy or clone the repo in your roles folder.
> 
> https://galaxy.ansible.com/tna76874/ansible_docker_jitsi

ok.

For example I have my personal config .env, how I can add it in and use?

**Comment by tna76874** [comment]
You might have a look in this repo, where I use the role within an ansible playbook.

https://github.com/tna76874/hdhweg-homeschooling-stack
